# -*- coding: utf-8 -*-
"""_2_🗺️_Mapa_de_Vendas_por_Região.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7hvy7cgCxZjYp__ySoCrUgKSQyJ0zQ4
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from utils.load_data import load_data

@st.cache_data
def get_sales_by_state():
    df = load_data()
    sales_by_state = df.groupby('customer_state')['price'].sum().reset_index()
    return sales_by_state

def main():
    st.header("🗺️ Mapa de Vendas por Estado")
    st.markdown("Concentração de vendas por região do Brasil.")

    sales_by_state = get_sales_by_state()

    fig = px.choropleth(
        sales_by_state,
        locations='customer_state',
        locationmode='country name',
        color='price',
        hover_name='customer_state',
        title='Faturamento Total por Estado',
        scope='south america'
    )
    st.plotly_chart(fig)

main()